name: VPN Ping Checker

on:
  workflow_dispatch:

jobs:
  check-vpn:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Run test
      run: python test_simple.py
    
    - name: Commit
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git add FREE-VPN-FROM-KIRILL.txt
        git diff --staged --quiet || git commit -m "Test update"
        git push
